$Resize:Stretch
Screen _NewImage(320, 200, 32), 0, 0, 1
_Font 8
' qb graphics settings ^^

f = FreeFile ' unused file access number, kinda weird way of doing it
' On Error GoTo 10


Type sounds
    door As Long
    money As Long ' haha
    gameplay_music As Long
    enemydeath As Long
    flameball As Long
    getHurt As Long
    gameOver_music As Long

    titleMusic As Long
    endMusic As Long
End Type

Type screenCards
    endCard As Long
    logo As Long
    tutorial As Long
    lore As Long
    gameOver As Long
    last As Long
End Type

Type enemy
    ttl As Integer ' countdown timer decides how long it waits before the next move
    alive As Integer
End Type

Type flame
    xdir As Integer
    ydir As Integer
    status As Integer
    ttl As Integer
    power As Integer
End Type


Type gameType
    money As Integer
    enemies As Integer
    power As Integer
    hp As Integer
    keys As Integer
    ' switch not needed anymore
End Type

Type graphics
    dragon As Long
    bricks As Long
    money As Long ' lol
    hero As Long
    door As Long
    flame As Long
    proj As Long
    spike As Long
    nextt As Long
End Type
' game types ^

Dim Shared map(50, 50) As Integer
Dim dragon& ' as LONG
Dim keyhit& ' as LONG
Dim level As Integer
level = 0
Dim Shared sfx As sounds
Dim Shared gfx As graphics
Dim Shared graphics_cards As screenCards
Dim game As gameType

Dim Shared enemies(50, 50) As enemy
Dim Shared flames(50, 50) As flame
Dim Shared projectiles(50, 50) As flame
Dim Shared spikes(50, 50) As flame

Call killAllEnemies
Call loadAllSounds
Call loadAllGraphics




' i actually hate this
'$include:'world.bas'
'$include:'world2.bas'
'$include:'world3.bas'
' tho i don't have a cleaner solution atm.
' THEY CONTAIN BIG DATA STATEMENTS FOR THE LEVELS, GENERATED BY A PROGRAM


'https://youtu.be/-vqQGdh2KmM


'Print titleMusic&

_SndVol sfx.titleMusic, .1
_SndLoop sfx.titleMusic




' game loop
Do
    titleSelect = runTitle
    Select Case titleSelect
        Case 1
            Call runGame

        Case 2
            Call runTutorial

    End Select
    ' run the title screen

Loop



Sleep

System



Sub runGame
    todo
End Sub

Sub runTutorial
    Call todo

End Sub

Sub todo
    Cls
    Print "workin on it"
    PCopy 0, 1
    Sleep
End Sub

Function runTitle
    Do
        escapeCondition = 0
        Do
            Cls
            _PutImage (0, 0), graphics_cards.logo&
            Print
            Print " PUSH P TO PLAY!"
            Print " PUSH T FOR TUTORIAL!"
            Locate 19, 25: Print "K. JASEY"
            Locate 20, 25: Print "2022"
            PCopy 0, 1
            _Delay .1

            k$ = InKey$
        Loop Until k$ <> ""
        Select Case k$
            Case "p"
                escapeCondition = 1 'GoTo game
            Case "t"
                escapeCondition = 2 ' GoTo tutorial
        End Select

    Loop Until escapeCondition <> 0
    runTitle = escapeCondition
End Function

Sub loadAllGraphics
    gfx.dragon = _LoadImage("graphics\dragon.png")
    gfx.bricks = _LoadImage("graphics\bricks.png")
    gfx.money = _LoadImage("graphics\money.png")
    gfx.hero = _LoadImage("graphics\hero.png")
    gfx.door = _LoadImage("graphics\door.png")
    gfx.flame = _LoadImage("graphics\flameball.png")
    gfx.proj = _LoadImage("graphics\poisonrock.png")
    gfx.spike = _LoadImage("graphics\spike.png")
    gfx.nextt = _LoadImage("graphics\next.png")

    graphics_cards.gameOver = _LoadImage("graphics\gameOver.png")
    graphics_cards.endCard = _LoadImage("graphics\endCard.png")
    graphics_cards.logo = _LoadImage("graphics\logo.bmp")
    graphics_cards.tutorial = _LoadImage("graphics\tutorial.png")
    graphics_cards.lore = _LoadImage("graphics\lore.png")
    graphics_cards.last = _LoadImage("graphics\lastimg.png")
End Sub

Sub loadAllSounds
    sfx.door = _SndOpen("audio\door.wav")
    sfx.money = _SndOpen("audio\money.wav")
    sfx.enemydeath = _SndOpen("audio\enemy_death.wav")
    sfx.gameplay_music = _SndOpen("audio\dragon world.wav")
    sfx.flameball = _SndOpen("audio\flameBall.wav")
    sfx.getHurt = _SndOpen("audio\getHurt.wav")
    sfx.gameOver_music = _SndOpen("audio\funk.wav")
    sfx.titleMusic = _SndOpen("audio\dragon_savior_title.wav")
    sfx.endMusic = _SndOpen("audio\talk the talk.wav")
End Sub

Sub killAllEnemies
    For x = 0 To 49
        For y = 0 To 49
            enemies(x, y).alive = 0
        Next y
    Next x
End Sub


